### ISSUE TITLE
Error in windows

### ISSUE THREAD

**Issue by HypsterOP** [hackorum/VapourNvim#23] opened 2021-09-07 17:05 UTC
Vim(packadd):E919: Directory not found in 'packpath' : 'pack/*/opt/nvim-lspconfig'

**Comment by hackorum** [comment] 2021-09-08 09:27
Could you please share a screenshot or video of when the error occurs?

**Comment by H4ckint0sh** [comment] 2021-09-08 09:35
![Skärmavbild 2021-09-08 kl  11 34 56](https://user-images.githubusercontent.com/44159647/132485119-f56dd868-d384-462f-9208-02c5948aa190.png)

**Comment by HypsterOP** [comment] 2021-09-08 09:54
> 
> 
> Could you please share a screenshot or video of when the error occurs?

Yes, could you wait for a couple of minutes im finishing a school assignment.

**Comment by HypsterOP** [comment] 2021-09-08 09:54
> 
> 
> ![Skärmavbild 2021-09-08 kl 11 34 56](https://user-images.githubusercontent.com/44159647/132485119-f56dd868-d384-462f-9208-02c5948aa190.png)

yes i have the same error

**Comment by hackorum** [comment] 2021-09-08 10:58
What is the output of :set setrtp

**Comment by hackorum** [comment] 2021-09-08 10:58
And does this occur every time you open nvim?

**Comment by HypsterOP** [comment] 2021-09-08 10:59
Also i tried it _**again.**_, and when i'm trying to sync the plugins...[error](https://ibb.co/xFHySFs)

**Comment by HypsterOP** [comment] 2021-09-08 11:00
> 
> 
> And does this occur every time you open nvim?

yes

**Comment by HypsterOP** [comment] 2021-09-08 11:02
> 
> 
> What is the output of :set setrtp

Unknown Option: setrtp

**Comment by hackorum** [comment] 2021-09-08 11:43
I tried on fresh installs of windows, linux and also macos but I was not able to reproduce it.

**Comment by H4ckint0sh** [comment] 2021-09-08 13:40
I tried this on 3 machines (all mac) and the same error occurred in all 3.

**Comment by hackorum** [comment] 2021-09-09 15:02
Does upgrade to 0.6 work?

**Comment by H4ckint0sh** [comment] 2021-09-09 17:01
If you mean Neovim 0.6. I have altardy tried it and got the same error.

**Comment by hackorum** [comment] 2021-09-10 10:59
It was an issue with nvim-autopairs. The after keyword was set to {'nvim-compe'} even when compe was disabled. Fixed in 7a0ebab

**Closed by hackorum** 2021-09-10 10:59 UTC
